name: '[monorepo] yarn install'
description: 'Run yarn install with node_modules linked and cache enabled'
inputs:
  yarn-download-cache-key:
    description: 'Yarn rotates downloaded cache archives. In case of issue you can update the key.'
    required: false
    default: 'v1'

runs:
  using: 'composite'

  steps:
    - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
      with:
        node-version: 16

    - name: 📇 Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    # Yarn rotates the downloaded cache archives.
    # Keep one global cache-entry through action/cache
    - name: ⤵️  Restore yarn cache
      uses: actions/cache@v3
      id: yarn-download-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-download-cache-${{ inputs.yarn-download-cache-key }}

    # Invalidated on yarn.lock changes
    - name: 📀 Restore yarn install state
      id: yarn-install-state-cache
      uses: actions/cache@v3
      with:
        path: |
          .ci-cache/yarn-state
        key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}

    - name: 📥 yarn install
      shell: bash
      working-directory: ./
      run: |
        yarn --immutable && cd apps/mobile && yarn --immutable
      env:
        # CI optimizations. Overrides yarnrc.yml options (or their defaults) in the CI action.
        YARN_ENABLE_GLOBAL_CACHE: 'false' # Use local cache folder to keep downloaded archives
        YARN_NM_MODE: 'hardlinks-local' # Hardlinks-local reduces io / node_modules size
        YARN_INSTALL_STATE_PATH: .ci-cache/yarn-state/install-state.gz # Small speedup when lock does not change
        HUSKY: '0' # By default do not run HUSKY install

    - name: 👷 Compile mobile contracts
      uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
      with:
        timeout_minutes: 3
        retry_wait_seconds: 20
        max_attempts: 3
        command: yarn mobile contracts:compile
