name: Setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org
        cache: yarn

    - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
      id: install-cache
      with:
        path: node_modules/
        key: ${{ runner.os }}-install-${{ hashFiles('**/yarn.lock') }}

    - if: steps.install-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --ignore-scripts
      shell: bash
