coverage:
  status:
    project:
      default:
        target: auto # each pr must increase coverage
        threshold: 0.5% # adjust for flakiness
    patch:
      default:
        target: auto
        threshold: 0%
        informational: true # pass coverage no matter coverage

comment:
  layout: "reach, diff, files"
