name: '[mobile] fastlane deploy'

description: 'Deploys fastlane for the given environment and app identifiers'
inputs:
  branch:
    description: 'the branch to run this deployment for'
    required: true
  configuration:
    description: 'the iOS deploy configuration for this deployment'
    required: true
  sentry-env:
    description: 'the sentry env for this deployment'
    required: true
  apple-app-id:
    description: 'the apple app id for this deployment'
    required: true
  app-identifier:
    description: 'the apple app identifier for this deployment'
    required: true
  onesignal-app-id:
    description: 'the onesignal app id for this deployment'
    required: true
  uniswap-api-key:
    description: 'passed secret value'
    required: true
  sentry-dsn:
    description: 'passed secret value'
    required: true
  statsig-api-key:
    description: 'passed secret value'
    required: true
  statsig-proxy-url:
    description: 'passed secret value'
    required: true
  amplitude-experiments-deploy-key:
    description: 'passed secret value'
    required: true
  infura-project-id:
    description: 'passed secret value'
    required: true
  moonpay-api-key:
    description: 'passed secret value'
    required: true
  moonpay-api-url:
    description: 'passed secret value'
    required: true
  moonpay-widget-api-url:
    description: 'passed secret value'
    required: true
  walletconnect-project-id:
    description: 'passed secret value'
    required: true
  apple-id:
    description: 'passed secret value'
    required: true
  apple-team-id:
    description: 'passed secret value'
    required: true
  app-store-connect-key-id:
    description: 'passed secret value'
    required: true
  app-store-connect-issuer-id:
    description: 'passed secret value'
    required: true
  app-store-connect-key-content:
    description: 'passed secret value'
    required: true
  match-password:
    description: 'passed secret value'
    required: true
  ci-keychain-password:
    description: 'passed secret value'
    required: true
  github-token:
    description: 'passed secret value'
    required: true
  url-to-fastlane-certificates-repo:
    description: 'passed secret value'
    required: true
  sentry-auth-token:
    description: 'passed secret value'
    required: true
  sentry-org:
    description: 'passed secret value'
    required: true
  sentry-project:
    description: 'passed secret value'
    required: true
  appsflyer-api-key:
    description: 'passed secret value'
    required: true
  appsflyer-app-id:
    description: 'passed secret value'
    required: true
  quicknode-bnb-rpc-url:
    description: 'passed secret value'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: styfle/cancel-workflow-action@860d4c7374d6e4a1c482e80897cb913ae46692ac
      with:
        all_but_latest: true

    # Set up xcode version
    - uses: maxim-lobanov/setup-xcode@4aa4176a819ae7c019451acfda0bba67bffc6704
      with:
        xcode-version: '15'

    - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
      with:
        fetch-depth: 0
        ref: ${{ inputs.branch }}

    # Set path variables needed for caches
    - name: 𝒳 Set workflow variables
      shell: bash
      id: workflow-variables
      run: |
        echo "::set-output name=xcode-version::$(xcodebuild -version|tail -1|cut -f3 -d' ')"

    # Detox is compiled during yarn install, using Xcode, set up cache first
    - uses: hendrikmuhs/ccache-action@ed038da2f2f09b0c8387c00e1498290a4808da2e
      name: 🧑‍💻 Xcode Compile Cache
      with:
        key: ${{ runner.os }}-v2 # makes a unique key w/related restore key internally
        max-size: 400M

    - name: 📥 Install
      uses: ./.github/actions/monorepo_yarn_install

    - name: Update Ruby build tools
      uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
      with:
        timeout_minutes: 2
        retry_wait_seconds: 2
        max_attempts: 3
        command: gem update cocoapods xcodeproj

    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      name: 📀 Cache Pods
      id: pods-cache
      with:
        path: tests/ios/Pods
        key: ${{ runner.os }}-pods-v2-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: ${{ runner.os }}-pods-v2

    - name: 🗄️ Copy over env variables
      uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
      with:
        timeout_minutes: 20
        retry_wait_seconds: 2
        max_attempts: 3
        command: yarn mobile env:local:copy:swift
      env:
        UNISWAP_API_KEY: ${{ inputs.uniswap-api-key }}

    - name: 🫛 Pod Install
      uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
      with:
        timeout_minutes: 20
        retry_wait_seconds: 2
        max_attempts: 3
        command: cd apps/mobile/ios && pod install && cd ..

    - name: 🦤 Generate GraphQL schemas and queries for Swift
      uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
      with:
        timeout_minutes: 3
        retry_wait_seconds: 20
        max_attempts: 3
        command: yarn mobile graphql:generate:swift

    - name: Check Sensitive File Changes
      uses: ./.github/actions/sensitive_files_changed

    - name: 🐞 Create Sentry release
      working-directory: ./apps/mobile
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
        SENTRY_ORG: ${{ inputs.sentry-org }}
        SENTRY_PROJECT: ${{ inputs.sentry-project }}
        APP_IDENTIFIER: ${{ inputs.app-identifier }}
      shell: bash
      run: |
        # Install Sentry CLI
        curl -sL https://sentry.io/get-cli/ | bash

        # Create new Sentry release
        export SENTRY_RELEASE="$APP_IDENTIFIER@$IOS_VERSION_NUMBER+$IOS_BUILD_NUMBER"
        sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE --log-level=info
        sentry-cli releases set-commits $SENTRY_RELEASE --auto --ignore-missing --log-level=info

        # Create new deploy for this Sentry release
        sentry-cli releases deploys $SENTRY_RELEASE new -e ${{ inputs.sentry-env }}

    - name: 📲 Build + deploy iOS app
      working-directory: ./apps/mobile
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
        export CCACHE_FILECLONE=true
        export CCACHE_DEPEND=true
        export CCACHE_INODECACHE=true
        ccache -s
        set -o pipefail
        fastlane ios buildAndShip
        ccache -s
      shell: bash
      env:
        UNISWAP_API_KEY: ${{ inputs.uniswap-api-key }}
        SENTRY_DSN: ${{ inputs.sentry-dsn }}
        STATSIG_API_KEY: ${{ inputs.statsig-api-key }}
        STATSIG_PROXY_URL: ${{ inputs.statsig-proxy-url }}
        AMPLITUDE_EXPERIMENTS_DEPLOYMENT_KEY: ${{ inputs.amplitude-experiments-deploy-key }}
        INFURA_PROJECT_ID: ${{ inputs.infura-project-id }}
        MOONPAY_API_KEY: ${{ inputs.moonpay-api-key }}
        MOONPAY_API_URL: ${{ inputs.moonpay-api-url }}
        MOONPAY_WIDGET_API_URL: ${{ inputs.moonpay-widget-api-url }}
        APPSFLYER_API_KEY: ${{ inputs.appsflyer-api-key }}
        APPSFLYER_APP_ID: ${{ inputs.appsflyer-app-id }}
        ONESIGNAL_APP_ID: ${{ inputs.onesignal-app-id }}
        WALLETCONNECT_PROJECT_ID: ${{ inputs.walletconnect-project-id }}
        APP_IDENTIFIER: ${{ inputs.app-identifier }}
        APPLE_ID: ${{ inputs.apple-id }}
        APPLE_APP_ID: ${{ inputs.apple-app-id }}
        APPLE_TEAM_ID: ${{ inputs.apple-team-id }}
        APP_STORE_CONNECT_KEY_ID: ${{ inputs.app-store-connect-key-id }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ inputs.app-store-connect-issuer-id }}
        APP_STORE_CONNECT_KEY_CONTENT: ${{ inputs.app-store-connect-key-content }}
        MATCH_PASSWORD: ${{ inputs.match-password }}
        CI: true
        CI_KEYCHAIN_NAME: 'CI_KEYCHAIN'
        CI_KEYCHAIN_PASSWORD: ${{ inputs.ci-keychain-password }}
        CONFIGURATION: ${{ inputs.configuration }}
        GIT_BRANCH_NAME: ${{ github.ref }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        URL_TO_FASTLANE_CERTIFICATES_REPO: ${{ inputs.url-to-fastlane-certificates-repo }}
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
        SENTRY_ORG: ${{ inputs.sentry-org }}
        SENTRY_PROJECT: ${{ inputs.sentry-project }}
        QUICKNODE_BNB_RPC_URL: ${{ inputs.quicknode-bnb-rpc-url }}
