name: 1 | Push main -> staging

# This CI job is responsible for pushing the current contents of the `main` branch to the
# `releases/staging` branch, which will in turn kick off a deploy to the staging environment.

on:
  workflow_dispatch:

# https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action
jobs:
  push-staging:
    name: 'Push to staging branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - run: touch src/locales/en-US.po
      - name: Download translations
        uses: crowdin/github-action@3133cc916c35590475cf6705f482fb653d8e36e9
        with:
          upload_sources: false
          download_translations: true
          project_id: 458284
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN_SECRET }}
          source: 'src/locales/en-US.po'
          translation: 'src/locales/%locale%.po'
          localization_branch_name: t9n/download
          commit_message: 'chore(i18n): synchronize translations from crowdin [skip ci]'
          create_pull_request: false
          push_translations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git status
      - name: Git push
        run: |
          git push origin t9n/download:t9n/test --force
