name: Check PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  # Ensures that the PR title adheres to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
  conventional-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@db6e259b93f286e3416eef27aaae88935d16cf2e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
