name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      # uses v1 to get full git history to track changes
      - uses: actions/checkout@v1
      - name: Yarn Install
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn --no-audit --prefer-offline
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          buildScriptName: storybook:build
          # positive exit of action even when there are changes detected
          exitZeroOnChanges: true
          # skip waiting for build results
          exitOnceUploaded: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
