name: Crowdin Download

on:
  schedule:
    # Download translations every hour.
    # This is not done as part of the build so that builds remain reproducible.
    - cron: '0 * * * *'
  # manual trigger
  workflow_dispatch:

jobs:
  download-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: ./.github/actions/setup
      - run: yarn i18n:extract

      - name: Download Crowdin translations
        uses: crowdin/github-action@ecd7eb0ef6f3cfa16293c79e9cbc4bc5b5fd9c49
        with:
          upload_sources: false
          download_translations: true
          project_id: 458284
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN_SECRET }}
          source: 'src/locales/en-US.po'
          translation: 'src/locales/%locale%.po'
          create_pull_request: true
          pull_request_title: 'chore(i18n): new Crowdin translations'
          localization_branch_name: l10n_crowdin
          commit_message: 'chore(i18n): synchronize translations from crowdin [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
