name: Crowdin Upload

on:
  push:
    branches:
      - main

jobs:
  upload-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: ./.github/actions/setup
      - run: yarn i18n:extract

      - name: Upload Crowdin sources
        uses: crowdin/github-action@331321924bd16fd3b1cf1d693c6bc35047e70ba0
        with:
          upload_sources: true
          download_translations: false
          project_id: 458284
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN_SECRET }}
          source: 'src/locales/en-US.po'
          translation: 'src/locales/%locale%.po'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
