name: Code Quality Checks
# https://github.com/invertase/react-native-firebase/blob/master/.github/workflows/linting.yml

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  linting:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-yarn-v1

      - name: Yarn Install
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn --no-audit --prefer-offline

      - name: Typechain
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          retry_wait_seconds: 20
          max_attempts: 3
          command: yarn contracts:compile

      - name: Lint
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          retry_wait_seconds: 10
          max_attempts: 3
          command: yarn lint

  typescript:
    name: TypeScript Build Validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-yarn-v1

      - name: Yarn Install
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn --no-audit --prefer-offline

      - name: Typechain
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          retry_wait_seconds: 20
          max_attempts: 3
          command: yarn contracts:compile

      - name: Typescript Compile
        run: yarn tsc:compile
