name: '[mobile] Update Build Numbers'
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0" # “At 12:00 UTC on Sunday.”

jobs:
  update-build-numbers:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
        with:
          fetch-depth: 1

      - name: Update Dev configuration build numbers
        env:
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER_DEV }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
          CONFIGURATION: "Dev"
        run: cd apps/mobile && fastlane ios update_build_numbers

      - name: Update Beta configuration build numbers
        env:
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER_BETA }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
          CONFIGURATION: "Beta"
        run: cd apps/mobile && fastlane ios update_build_numbers

      - name: Update Prod configuration build numbers
        env:
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER_PROD }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
          CONFIGURATION: "Release"
        run: cd apps/mobile && fastlane ios update_build_numbers

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672
        with:
          token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
          commit-message: "[bot] Update build numbers"
          committer: UL Mobile Service Account <hello-happy-puppy@users.noreply.github.com>
          author: UL Mobile Service Account <hello-happy-puppy@users.noreply.github.com>
          signoff: false
          branch: chore/update-build-numbers
          delete-branch: true
          title: "chore: [bot] Update build numbers"
          body: Build numbers for dev, beta, and/or prod have been updated.
