name: '[monorepo] Integrity'

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  monorepo-integrity:
    name: Check integrity
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 📥 Install
        uses: ./.github/actions/monorepo_yarn_install

      - name: 👬🏽 Check for conflicting versions across the monorepo
        run: yarn g:check:deps

      - name: 👬🏽 Check for duplicate dependencies in lock file
        run: yarn dedupe --check

      - name: 🧑‍⚖️ Check for yarn constraints.pro
        run: yarn constraints
