name: '[monorepo] Code Quality Checks'

on:
  workflow_call:

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-test:
    name: Typecheck, Lint, Build, and Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 📥 Install
        uses: ./.github/actions/monorepo_yarn_install

      - name: 🕵️  Typecheck
        run: yarn g:typecheck

      - name: 🔬 Lint
        run: yarn g:lint

      - name: 🏗  Build
        run: yarn g:build

      - name: 🧪 Unit Tests
        run: yarn g:test

      - name: 🫢 Upload coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: ⚠️  Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

