name: Push changes to releases/beta

# This CI job is responsible for pushing the current contents of the `main` branch to the
# releases/beta branch, which is the branch where the GitHub action for building the beta
# app version will take its code. It can be triggered via a button in the GitHub actions UI.

on:
  workflow_dispatch:

# https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action
jobs:
  beta-branch-push:
    name: 'Push to releases/beta Branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
        with:
          token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
          ref: main
      - name: Setup Git
        run: |
          git config user.name "UL Mobile Service Account"
          git config user.email "hello-happy-puppy@users.noreply.github.com"
      - name: Push to Beta Release Branch
        run: |
          git push -u origin main:releases/beta --force
