name: Release
on:
  schedule:
    - cron: '0 12 * * 1-4' # every day 12:00 UTC Monday-Thursday
  # manual trigger
  workflow_dispatch:

jobs:
  wait-on-tests:
    runs-on: ubuntu-latest
    steps:
      - id: unit-tests
        uses: fountainhead/action-wait-for-check@4699210ccc66e2a13260803fadbb77085421b891
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: unit-tests
      - id: cypress-tests
        uses: fountainhead/action-wait-for-check@4699210ccc66e2a13260803fadbb77085421b891
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: cypress-tests
      - if: steps.unit-tests.outputs.conclusion != 'success' || steps.cypress-tests.outputs.conclusion != 'success'
        run: exit 1

  tag:
    needs: wait-on-tests
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.github-tag-action.outputs.new_tag }}
      changelog: ${{ steps.github-tag-action.outputs.changelog }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Bump and tag
        id: github-tag-action
        uses: mathieudutour/github-tag-action@d745f2e74aaf1ee82e747b181f7a0967978abee0@
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*
          default_bump: patch

  release:
    needs: tag
    if: ${{ needs.tag.outputs.new_tag != null }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: ./.github/actions/setup
      - run: yarn prepare
      - run: yarn build

      - name: Pin to IPFS
        id: pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@39bbda1ce1fe24c69c6f57861b8038278d53688d
        with:
          pin-name: Uniswap ${{ needs.tag.outputs.new_tag }}
          path: './build'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      - name: Pin to Crust
        uses: crustio/ipfs-crust-action@7be16b7c0185a3dab3af5fd05b7d618b3012048f
        continue-on-error: true
        timeout-minutes: 2
        with:
          cid: ${{ steps.upload.outputs.hash }}
          seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Convert CIDv0 to CIDv1
        id: convert-cidv0
        uses: uniswap/convert-cidv0-cidv1@eaa60912a8b68eae19b1c6635e74202071da5a97
        with:
          cidv0: ${{ steps.pinata.outputs.hash }}

      - name: Release
        uses: actions/create-release@c9ba6969f07ed90fae07e2e66100dd03f9b1a50e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.new_tag }}
          release_name: Release ${{ needs.tag.outputs.new_tag }}
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ steps.pinata.outputs.hash }}`
            - CIDv1: `${{ steps.convert-cidv0.outputs.cidv1 }}`

            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.uniswap.org](https://app.uniswap.org).

            You can also access the Uniswap Interface directly from an IPFS gateway.
            **BEWARE**: The Uniswap interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as which tokens you have imported.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.uniswap.org](https://app.uniswap.org).
            Your Uniswap settings are never remembered across different URLs.

            IPFS gateways:
            - https://${{ steps.convert-cidv0.outputs.cidv1 }}.ipfs.dweb.link/
            - https://${{ steps.convert-cidv0.outputs.cidv1 }}.ipfs.cf-ipfs.com/
            - [ipfs://${{ steps.upload.outputs.hash }}/](ipfs://${{ steps.pinata.outputs.hash }}/)

            ${{ needs.tag.outputs.changelog }}

      - name: Setup node@16 (required by Cloudflare Pages)
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16

      - name: Update Cloudflare Pages deployment
        uses: cloudflare/pages-action@364c7ca09a4b57837c5967871d64a2c31adb8c0d
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: build
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload source maps to Sentry
        uses: getsentry/action-release@bd5f874fcda966ba48139b0140fb3ec0cb3aabdd 
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: './build/static/js'
          url_prefix: '/static/js'