name: 2 | [web] Push production

# This CI job is responsible for pushing the content of web/staging to web/production.
# It must be approved by web-reviewers, as enforced by environment protection rules.

on:
  workflow_dispatch:

jobs:
  push-prod:
    name: 'Push to web/production'
    runs-on: ubuntu-latest
    environment:
      name: web/push/production
    steps:
      - name: Check test status
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const statuses = await github.rest.repos.listCommitStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            })
            const status = statuses.data.find(status => status.context === 'Test / promotion')?.state || 'missing'
            core.info('Status: ' + status)
            if (status !== 'success') {
              core.setFailed('"Test / promotion" must be successful before pushing')
            }

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
          ref: web/staging

      - name: Git config
        run: |
          git config user.name "UL Service Account"
          git config user.email "hello-happy-puppy@users.noreply.github.com"

      - name: Git push
        run: |
          git push origin web/staging:web/production --force
